#!/bin/bash
~/gem5/build/X86/gem5.opt -d chkp1_test -r -e ~/gem5/configs/deprecated/example/se.py --restore-simpoint-checkpoint --checkpoint-dir checkpoints -r 1 --cpu-type=NonCachingSimpleCPU --restore-with-cpu=X86NonCachingSimpleCPU -c astar_base.gcc43-64bit --options "lake.cfg";
~/gem5/build/X86/gem5.opt -d chkp2_test -r -e ~/gem5/configs/deprecated/example/se.py --restore-simpoint-checkpoint --checkpoint-dir checkpoints -r 2 --cpu-type=NonCachingSimpleCPU --restore-with-cpu=X86NonCachingSimpleCPU -c astar_base.gcc43-64bit --options "lake.cfg";
~/gem5/build/X86/gem5.opt -d chkp3_test -r -e ~/gem5/configs/deprecated/example/se.py --restore-simpoint-checkpoint --checkpoint-dir checkpoints -r 3 --cpu-type=NonCachingSimpleCPU --restore-with-cpu=X86NonCachingSimpleCPU -c astar_base.gcc43-64bit --options "lake.cfg";
~/gem5/build/X86/gem5.opt -d chkp4_test -r -e ~/gem5/configs/deprecated/example/se.py --restore-simpoint-checkpoint --checkpoint-dir checkpoints -r 4 --cpu-type=NonCachingSimpleCPU --restore-with-cpu=X86NonCachingSimpleCPU -c astar_base.gcc43-64bit --options "lake.cfg";
~/gem5/build/X86/gem5.opt -d chkp5_test -r -e ~/gem5/configs/deprecated/example/se.py --restore-simpoint-checkpoint --checkpoint-dir checkpoints -r 5 --cpu-type=NonCachingSimpleCPU --restore-with-cpu=X86NonCachingSimpleCPU -c astar_base.gcc43-64bit --options "lake.cfg";
~/gem5/build/X86/gem5.opt -d chkp6_test -r -e ~/gem5/configs/deprecated/example/se.py --restore-simpoint-checkpoint --checkpoint-dir checkpoints -r 6 --cpu-type=NonCachingSimpleCPU --restore-with-cpu=X86NonCachingSimpleCPU -c astar_base.gcc43-64bit --options "lake.cfg";
~/gem5/build/X86/gem5.opt -d chkp7_test -r -e ~/gem5/configs/deprecated/example/se.py --restore-simpoint-checkpoint --checkpoint-dir checkpoints -r 7 --cpu-type=NonCachingSimpleCPU --restore-with-cpu=X86NonCachingSimpleCPU -c astar_base.gcc43-64bit --options "lake.cfg";
~/gem5/build/X86/gem5.opt -d chkp8_test -r -e ~/gem5/configs/deprecated/example/se.py --restore-simpoint-checkpoint --checkpoint-dir checkpoints -r 8 --cpu-type=NonCachingSimpleCPU --restore-with-cpu=X86NonCachingSimpleCPU -c astar_base.gcc43-64bit --options "lake.cfg";
~/gem5/build/X86/gem5.opt -d chkp9_test -r -e ~/gem5/configs/deprecated/example/se.py --restore-simpoint-checkpoint --checkpoint-dir checkpoints -r 9 --cpu-type=NonCachingSimpleCPU --restore-with-cpu=X86NonCachingSimpleCPU -c astar_base.gcc43-64bit --options "lake.cfg";
~/gem5/build/X86/gem5.opt -d chkp10_test -r -e ~/gem5/configs/deprecated/example/se.py --restore-simpoint-checkpoint --checkpoint-dir checkpoints -r 10 --cpu-type=NonCachingSimpleCPU --restore-with-cpu=X86NonCachingSimpleCPU -c astar_base.gcc43-64bit --options "lake.cfg";
~/gem5/build/X86/gem5.opt -d chkp11_test -r -e ~/gem5/configs/deprecated/example/se.py --restore-simpoint-checkpoint --checkpoint-dir checkpoints -r 11 --cpu-type=NonCachingSimpleCPU --restore-with-cpu=X86NonCachingSimpleCPU -c astar_base.gcc43-64bit --options "lake.cfg";
~/gem5/build/X86/gem5.opt -d chkp12_test -r -e ~/gem5/configs/deprecated/example/se.py --restore-simpoint-checkpoint --checkpoint-dir checkpoints -r 12 --cpu-type=NonCachingSimpleCPU --restore-with-cpu=X86NonCachingSimpleCPU -c astar_base.gcc43-64bit --options "lake.cfg";
~/gem5/build/X86/gem5.opt -d chkp13_test -r -e ~/gem5/configs/deprecated/example/se.py --restore-simpoint-checkpoint --checkpoint-dir checkpoints -r 13 --cpu-type=NonCachingSimpleCPU --restore-with-cpu=X86NonCachingSimpleCPU -c astar_base.gcc43-64bit --options "lake.cfg";
~/gem5/build/X86/gem5.opt -d chkp14_test -r -e ~/gem5/configs/deprecated/example/se.py --restore-simpoint-checkpoint --checkpoint-dir checkpoints -r 14 --cpu-type=NonCachingSimpleCPU --restore-with-cpu=X86NonCachingSimpleCPU -c astar_base.gcc43-64bit --options "lake.cfg";
~/gem5/build/X86/gem5.opt -d chkp15_test -r -e ~/gem5/configs/deprecated/example/se.py --restore-simpoint-checkpoint --checkpoint-dir checkpoints -r 15 --cpu-type=NonCachingSimpleCPU --restore-with-cpu=X86NonCachingSimpleCPU -c astar_base.gcc43-64bit --options "lake.cfg";
